version: '3.8'

services:
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
    command: ["bun", "run", "--watch", "server/index.ts"]
    # Add development tools
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging if needed 